### ISSUE TITLE
Removal of TFL Rail

### ISSUE THREAD

**Issue by stevehop** [robmarkcole/London-tube-status#11]
TFL have removed the 'TFL Rail' line from their API with the addition of the Elizabeth Line so this needs removing.

https://api.tfl.gov.uk/line/mode/tflrail/status no longer returns any data

**Comment by robmarkcole** [comment]
Any chance of a PR? I'm quite busy with a newborn baby

**Comment by robmarkcole** [comment]
Which lines does that drop?

**Comment by stevehop** [comment]
> Which lines does that drop

The Elizabeth Line replaces the Shenfield to Liverpool Street TFL Rail Line in the East and Heathrow/Reading to Paddington line in the West.

I'll try to do a PR, I've not done one before but I'm happy to give it a go and have already made a start.

Congrats for your newborn, plenty of work and not much sleep for you then

**Comment by robmarkcole** [comment]
closed in https://github.com/robmarkcole/London-tube-status/pull/12
