### ISSUE TITLE
New Overground lines not pulling through into HA London Underground component

### ISSUE THREAD

**Issue by stevehop** [robmarkcole/London-tube-status#13]
Hi @robmarkcole the London Overground line has been split into the following lines:

- "Liberty",
- "Lioness",
- "Mildmay",
- "Suffragette",
- "Weaver",
- "Windrush",

I can see these in the [API URL](https://api.tfl.gov.uk/line/mode/tube,overground,dlr,elizabeth-line/status) however simply adding the new names to the [Home Assistant London Underground integration](https://github.com/jpbede/home-assistant-core/blob/0b54239ae58a33d54139bc24eac4a20d60d46ec7/homeassistant/components/london_underground/const.py) is not pulling these new lines in.

I've unsuccessfully looked through your code to see if there is anything filtering out these new lines (the only difference I can see between them and other lines is that their "modeName" is defined as "overground" and not "tube" and I'm not sure how the TFL API previously defined the now defunct Overground line) and my Python knowledge isn't sufficient to get an output from your module independent of Home Assistant. Any pointers on how to solve would be greatly appreciated. Thanks

**Comment by robmarkcole** [comment]
@stevehop this will require a PR on the HA codebase

**Comment by stevehop** [comment]
Thanks @robmarkcole , so you can see the new lines using your module?

A PR was made to add the new line names but apparently this wasn't sufficient but at least if they're showing in London-tube-status then I can concentrate on the HA integration

**Comment by robmarkcole** [comment]
Yes no PR required here as far as I can see

**Comment by prpr19xx** [comment]
How do you actually test this module in isolation?
The instructions are somewhat terse. I presume you need to follow the Development section commands?
OK, it gets as far as "Run tests with venv/bin/pytest tests/*" without too much trouble, but that fails with a "requests_mock" error. I guess that's a missing line from the requirements-dev.txt file?
It seems to be solvable with a "pip install requests_mock" and then repeating just generates this:
```
======================================================= FAILURES =======================================================
____________________________________________________ test_tube_data ____________________________________________________

    def test_tube_data():
        """Test TubeData."""
        with requests_mock.Mocker() as mock_req:
            url = lts.API_URL
            mock_req.get(url, text=json.dumps(VALID_RESPONSE))
>           test_tube_data = lts.TubeData()
E           TypeError: TubeData.__init__() missing 1 required positional argument: 'session'

tests/test_london_tube_status.py:32: TypeError
=============================================== short test summary info ================================================
FAILED tests/test_london_tube_status.py::test_tube_data - TypeError: TubeData.__init__() missing 1 required positional argument: 'session'
================================================== 1 failed in 0.12s ===================================================
```

Also, the development/development.ipynb file (I've no idea what this is used for) still refers to tflrail:
development/development.ipynb:    "https://api.tfl.gov.uk/line/mode/tube,overground,dlr,tflrail/status\n",
development/development.ipynb:    "url = 'https://api.tfl.gov.uk/line/mode/tube,overground,dlr,tflrail/status'\n",
development/development.ipynb:      "  'modeName': 'tflrail',\n",

as does the link in the Edit Repository Details Website box on the Github web page.

**Comment by stevehop** [comment]
I had the same issue @prpr19xx when I tested. My understanding was that an .ipynb file was basically a code notebook and doesn't affect the actual running of the .py module but then I may be completely wrong.

What I find strange is that the HA integration is expecting a particular list of lines from london_tube_status because adding new lines to the config doesn't cause an error, even though it won't display them, if you take away an expected line, in this case 'London Overground' it errors out and won't setup. Other than the 'development.ipynb' file I can see no explicit mention of the line names anywhere outside of the HA module

**Comment by prpr19xx** [comment]
I had removed the "London Overground" line from HA's configuration.yaml
Putting it back makes everything work, but not having it doesn't generate any error - it just stops things working. This is rather annoying behaviour on HA's part. I have submitted a PR for HA to remove that line at least.

Anyway, there are still things in this repository that need fixing to be able test it in isolation.
